### ISSUE TITLE
Consider building against a fixed Capn Proto target

### ISSUE THREAD

**Issue by MikePopoloski** [chipsalliance/UHDM#483]
It would be nice if UHDM targeted a specific Capn Proto release instead of living at head via a submodule, for interoperability purposes. Each commit to the upstream repo can potentially break any consumer that isn't compiled against exactly the same commit, which increases in likelihood if there are other users of UHDM besides Surelog.

It seems easier to just rely on whatever version is installed on the system (using FindPackage in cmake). On Windows users will need to build the lib themselves but that's not really any different than how it works today.

**Comment by hzeller** [comment]
+1, this looks like someone with CMake-fu should be able to implement that easily.

Looking at debian packages, it looks like it comes with pkg-config packages
https://packages.debian.org/sid/amd64/libcapnp-dev/filelist

For windows users: Maybe there is also a similar devel package on chocolatey ?

**Comment by hzeller** [comment]
Also, this involves to generate the capnproto outputs in the CMakefile instead of the tcl-script.
