### ISSUE TITLE
The information about the Segmentation fault is little

### ISSUE THREAD

**Issue by 0616ygh** [chipsalliance/UHDM#612]
When we use UHDM+Yosys to debug our code, the prompt information of "Segmentation fault" is a little small. 
Could we add corresponding support in subsequent updates? T
hank you so much for your work and dedication.
![1111111](https://user-images.githubusercontent.com/97427070/148765860-62cf9999-439b-4e2a-bdd4-b61050bcc471.png)

**Comment by alaindargelas** [comment]
Hi @0616ygh,
please file these issues in https://github.com/antmicro/yosys-uhdm-plugin-integration/issues
