### ISSUE TITLE
can‘t detect width for identifier

### ISSUE THREAD

**Issue by little-blue** [chipsalliance/UHDM#614]
Another issue is that sometimes it can‘t detect width for identifier
![441639827906_ pic](https://user-images.githubusercontent.com/46994147/148922088-045fa0b2-b53d-4428-af9f-a3da99f8c613.jpg)

The code is like this
![截屏2022-01-11 下午6 12 51](https://user-images.githubusercontent.com/46994147/148923650-564a0d81-9555-417f-9c4e-b8ab444ecfec.png)

The definition of this variable is as follows：
![截屏2022-01-11 下午6 13 33](https://user-images.githubusercontent.com/46994147/148923736-0a0fc11b-da1c-496a-9ada-04c8bea2e413.png)

All documents are already referenced, so it's not a question of citing documents, but I need to manually change to this format to run
![截屏2022-01-11 下午6 07 46](https://user-images.githubusercontent.com/46994147/148922846-02bf4b74-89de-4b12-9ad8-583a6f612528.png)

**Comment by alaindargelas** [comment]
You are filing these errors on the wrong place, please file them in the uhdm-yosys integration plugin.
Also, do not use pictures, attach a full testcase in text.

**Comment by little-blue** [comment]
sorry, I will check and resubmit where appropriate
