### ISSUE TITLE
Run some type of function will meet error

### ISSUE THREAD

**Issue by little-blue** [chipsalliance/UHDM#615]
Just as the title, when the function has  the "output" local variable, It will meet error in uhdm. The error is like this:
![截屏2022-01-11 下午6 42 33](https://user-images.githubusercontent.com/46994147/148928605-79d1e517-0ad6-4f7b-a90e-caa9f0f783c6.png)
the code is like this 
![截屏2022-01-11 下午6 46 54](https://user-images.githubusercontent.com/46994147/148928802-a6754c48-60d8-4661-a9fa-4ed13adb63a1.png)
The function definition is this 
![截屏2022-01-11 下午6 47 21 1](https://user-images.githubusercontent.com/46994147/148929066-54736ff3-66b3-4b28-a381-db1aafa069ec.png)

When I expand this function where I use this function. The error disappear.

**Comment by alaindargelas** [comment]
Please add the example in text, not with a picture, I am not going to retype what is in the picture, I hope you understand :-)
Use 
```
text section 
```

Also the error is not coming from Surelog/UHDM, what executable are you running?
Same thing, please put the error and a bit more messages above the error in text, not picture.

**Comment by alaindargelas** [comment]
This error is filed in the wrong repo.

**Comment by little-blue** [comment]
Sorry, I didn't have the experience of submitting before, I will abide by the etiquette of submitting later, thank you for your teaching

**Comment by alaindargelas** [comment]
No problem, welcome to Github and UHDM!
