### ISSUE TITLE
Need to run git tagging in CI action - permission denied

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/UHDM#888]
I try to [tag the revision whose SoT is in the CMake file](https://github.com/chipsalliance/UHDM/blob/master/.github/workflows/main.yml#L266-L293) on push whenever it changes.

However, it looks like we need some additional permissions in the github action.
https://github.com/chipsalliance/UHDM/actions/runs/4495222394/jobs/7908625709

I don't have access to the 'settings' tab in UHDM, which I suspect I need to find the right settings.

Tagging a few people who might know how to achieve this
@mithro @kgugala @umarcor

**Comment by kgugala** [comment]
#889 attempts to fix this

**Comment by hzeller** [comment]
Looks like we need a bot account; @kgugala fills in details.

For now, I've just manually tagged the release, so that we can explore that permission issue separately.
