### ISSUE TITLE
Python binding should be conditional on a special option, not on BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by yurivict** [chipsalliance/UHDM#911]
[This code](https://github.com/chipsalliance/UHDM/blob/master/CMakeLists.txt#L408) makes ```add_subdirectory(python)``` conditional on ```BUILD_SHARED_LIBS```.

I think that this is a mistake.

Version: 1.54

**Comment by alaindargelas** [comment]
@Thomasb81 can you take a look at this and #901

**Comment by yurivict** [comment]
python binding should be conditional on a special option, like ```option(BUILD_PYTHON_BINDINGS [...])```, or it should ideally be a separate project, because bindings are essentially separate projects that people tend to bundle together with the main project.

**Comment by Thomasb81** [comment]
I can probably provide a PR for an option as suggest by @yurivict but not sure to understand the separate project option. 

Are you referring to cmake project or git dependency ?

**Comment by yurivict** [comment]
> Are you referring to cmake project or git dependency ?

I am referring to a separate git project for the Python binding.

For example, there is a Heyoka C++ project here: https://github.com/bluescarni/heyoka
And there is it's Python binding here: https://github.com/bluescarni/heyoka.py

If you would look at the Python binding itself - it has nothing to do with the C++ project, except that it links to it like any other dependency would. The Python binding is not a "part" of UHDM: The rest of UHDM does not use the Python binding code. The Python binding is a separate project that actually can be installed multiple times for multiple concurrent Python versions.

**Comment by Thomasb81** [comment]
> The Python binding is a separate project that actually can be installed multiple times for multiple concurrent Python versions.

What you say make sense, in particular if this additional project is host by chipsalliance. 
But sorry I don't feel concerned by this need. Also I see in the past weeks so many commit to fine tune the cmake build system between uhdm and surelog ... With my knowledge and understanding of cmake ; that's not a task for me. :)

**Comment by alaindargelas** [comment]
Fixed by #924.
To build the python API, please use:
make release-shared UHDM_WITH_PYTHON=ON
