### ISSUE TITLE
Expose ExprEval::size to Python

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/UHDM#998]
I received a request for exposing ExprEval::size (typespec*) to Python.
Since the python API is vpiHandle based, it would have to be something like:
int uhdm.size(vpiHandle h)

Since vpiSize is not filled for most objects, the need for the size function arises.

**Comment by Thomasb81** [comment]
Unfortunately not possible any time soon to support this.

If we go in this direction of exporting to python such helper method, I think we should have plan to support other helper method. (At least not a single one)
